### ISSUE TITLE
Explore portability of OpenShift 'Templates' CRD for publishing qubo templates.

### ISSUE THREAD

**Issue by usrbinkat** [ContainerCraft/Kargo3#6]
Problem: many repetitive typed fields are required to deploy similar but different vm's

Solution: Capabilities like that of OpenShift's 'Template' CRD type allow for simple iterative recycling of yaml formats in ways that are very useful for kubevirt hypervisor utilization.

Question: Can the Template CRD be deployed on vanilla Kubernetes?

**Comment by fabiand** [comment]
Sadly it can not be deployed on stock k8s - there were thgouhts to extract it from openshift into it's own controller ...

However, for VMs at least KubeVirt is implementing flavors (kubevirt/kubevirt#6026)  in order to make it easier to write VM definitions with less lines.

**Comment by usrbinkat** [comment]
Conclusion:

Use vm presets / VirtualMachineFlavor for ntemplating purposes.

REF:
  - https://github.com/kubevirt/kubevirt/blob/main/docs/vm-presets.md

**Comment by fabiand** [comment]
Presets are also interesting, but don't cover the complete API iirc Thus flavors.
